crop = input("Crop: ")
waterCon = float(input("Estimated annual water consumption (L/rai): "))
area = float(input("Nation-wide growing area (rai): "))
cropYield = float(input("Average crop yield per growing area (kg/rai): "))
price = float(input("Estimated wholesale price (bath/kg): "))

print(crop, " over ", area , "rai")
print("Total water usage: ",waterCon*area/1000, "ML" )
print("Total crop yield: ", cropYield*area )
print("Total earing: ", cropYield*area*price/1000000, "mil. baht")
print("Average crop yeild per water usage:", cropYield/waterCon, "kg/L")
print("Average earning per water usage: ", price/waterCon, "baht/L")
print("average earing per area: ", price/area, "bath/rai")